language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq imagemagick
install:
  - pip install pep8 --use-mirrors
  - pip install -r requirements.txt
script:
  - pep8 mpd/ --ignore=E501,E241,E128
  - convert resources/Next.xcf mpd/mobile/media/img/next.png
  - convert resources/Previous.xcf mpd/mobile/media/img/next.png
  - convert resources/Play.xcf mpd/mobile/media/img/play.png
  - convert resources/Pause.xcf mpd/mobile/media/img/pause.png
  - convert resources/Delete.xcf mpd/mobile/media/img/delete.png
  - convert resources/Icon.xcf mpd/mobile/media/img/apple-touch-icon.png
  
 
 
