language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq imagemagick
install:
  - pip install pep8 --use-mirrors
  - pip install -r requirements.txt
script:
  - pep8 mpd/ --ignore=E501,E241,E128
  - ./build_icons.sh
  
 
 
